// GENERATED by design-engine — typed site content.
// Placeholder personas/logos/stats are labeled; replace before launch.
/* eslint-disable */
const content = {
  "siteConfig": {
    "brand": "DollarWise",
    "tagline": "Master money management with our structured curriculum on currency denominations, banking systems, and financial literacy."
  },
  "nav": {
    "brand": "DollarWise",
    "links": [
      {
        "label": "Product",
        "href": "/product"
      },
      {
        "label": "About",
        "href": "/about"
      },
      {
        "label": "Pricing",
        "href": "/pricing"
      }
    ],
    "cta": {
      "label": "Get started",
      "href": "/"
    }
  },
  "footer": {
    "brand": "DollarWise",
    "tagline": "Master money management with our structured curriculum on currency denominations, banking systems, and financial literacy.",
    "columns": [
      {
        "heading": "Product",
        "links": [
          {
            "label": "Product",
            "href": "/product"
          },
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Pricing",
            "href": "/pricing"
          }
        ]
      },
      {
        "heading": "Company",
        "links": [
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/"
          }
        ]
      },
      {
        "heading": "Resources",
        "links": [
          {
            "label": "Home",
            "href": "/"
          }
        ]
      }
    ],
    "note": "Generated by design-engine \u2014 placeholder content is labeled and awaits real data."
  },
  "pages": {
    "landing": {
      "meta": {
        "title": "DollarWise - Learn U.S. Currency and Financial Basics",
        "description": "Master money management with our structured curriculum on currency denominations, banking systems, and financial literacy."
      },
      "hero": {
        "headline": "Learn U.S. Currency Basics Today",
        "subheadline": "Build confidence with money through our structured lessons on denominations, management, and banking systems. Designed for students from elementary school through adulthood.",
        "highlights": [
          "Clear explanations of Federal Reserve functions",
          "Practical exercises in currency handling"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        },
        "secondaryCta": {
          "label": "See the product",
          "href": "/product"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "8,500+",
            "label": "Learners Enrolled"
          },
          {
            "value": "4",
            "label": "Core Curriculum Modules"
          },
          {
            "value": "96%",
            "label": "Course Completion Rate"
          }
        ]
      },
      "cta": {
        "heading": "Ready to build your financial skills?",
        "sub": "Join our community and access the full learning path. No hidden fees or complex jargon. Just clear lessons on how money works in America.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/"
        }
      }
    },
    "product": {
      "meta": {
        "title": "DollarWise Product Page",
        "description": "Learn U.S. currency and financial skills through our structured curriculum."
      },
      "hero": {
        "headline": "Master U.S. Currency Fundamentals",
        "subheadline": "A clear path from counting coins to understanding the Federal Reserve system, designed for students of all ages.",
        "highlights": [
          "Step-by-step lessons on money management",
          "Real-world practice exercises included"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "15,000+",
            "label": "Active Learners"
          },
          {
            "value": "82%",
            "label": "Course Completion Rate"
          },
          {
            "value": "$9.99",
            "label": "Average Monthly Cost (Premium)"
          }
        ]
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Basic Financial Literacy",
            "body": "Start with the basics of saving, spending, and budgeting. Students learn how money works in daily life.",
            "id": "topic-0"
          },
          {
            "title": "Currency Denominations",
            "body": "Identify bills and coins accurately. Practice counting cash safely using real-world scenarios.",
            "id": "topic-1"
          },
          {
            "title": "Currency Management",
            "body": "Understand how to track expenses, avoid debt traps, and plan for future purchases like college or a car.",
            "id": "topic-2"
          },
          {
            "title": "Federal Reserve System",
            "body": "Explore the role of banks in the economy. Learn about interest rates and inflation without complex jargon.",
            "id": "topic-3"
          }
        ]
      },
      "pricing": {
        "eyebrow": "Pricing",
        "heading": "Simple, honest pricing",
        "sub": "Placeholder tiers \u2014 align with your real packaging.",
        "tiers": [
          {
            "name": "Starter",
            "price": "$0",
            "period": "",
            "description": "Evaluate with your own data.",
            "features": [
              "Single project",
              "Community support",
              "Core features"
            ],
            "cta": {
              "label": "Choose Starter",
              "href": "/"
            },
            "featured": false
          },
          {
            "name": "Team",
            "price": "$49",
            "period": "/mo",
            "description": "For working teams shipping weekly.",
            "features": [
              "Unlimited projects",
              "Priority support",
              "Integrations",
              "Audit log"
            ],
            "cta": {
              "label": "Choose Team",
              "href": "/"
            },
            "featured": true
          },
          {
            "name": "Enterprise",
            "price": "Custom",
            "period": "",
            "description": "Compliance, scale, and dedicated support.",
            "features": [
              "SSO/SAML",
              "Custom SLAs",
              "Dedicated environment",
              "Security review"
            ],
            "cta": {
              "label": "Choose Enterprise",
              "href": "/"
            },
            "featured": false
          }
        ]
      }
    },
    "about": {
      "meta": {
        "title": "About DollarWise | Financial Literacy Education",
        "description": "Learn about U.S. currency and money management with our accessible curriculum."
      },
      "hero": {
        "eyebrow": "Financial Education",
        "headline": "DollarWise: Trustworthy Financial Education for Parents seeking financial literacy for their children",
        "subheadline": "Built for teams that need results they can defend. Clear workflows, measurable outcomes, no black boxes.",
        "highlights": [
          "Trustworthy",
          "Comprehensive",
          "Accessible"
        ],
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "98%",
            "label": "Illustrative satisfaction rate"
          },
          {
            "value": "4x",
            "label": "Faster review cycles (placeholder)"
          },
          {
            "value": "24/7",
            "label": "Monitoring"
          },
          {
            "value": "SOC 2",
            "label": "Ready posture (target)"
          }
        ]
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Quickstart",
            "body": "Install, authenticate, and run your first request in under five minutes.",
            "code": "curl -X POST https://api.example.com/v1/run \\\n  -H 'Authorization: Bearer <token>'",
            "id": "topic-0"
          },
          {
            "title": "Core concepts",
            "body": "Projects, runs, and results \u2014 the three objects everything else builds on.",
            "id": "topic-1"
          },
          {
            "title": "API reference",
            "body": "Every endpoint, request shape, and error code, with examples.",
            "id": "topic-2"
          }
        ]
      },
      "testimonials": {
        "eyebrow": "Voices",
        "heading": "What early teams say (placeholder personas)",
        "quotes": [
          {
            "quote": "The first tool in this category our clinicians actually kept using after the pilot.",
            "name": "Dr. Amara Osei",
            "role": "Chief Medical Officer, Meridian Labs"
          },
          {
            "quote": "Setup took an afternoon. The audit trail alone justified the switch.",
            "name": "Jonas Feld",
            "role": "VP Engineering, Cobalt Systems"
          },
          {
            "quote": "Our board asked harder questions than any vendor demo \u2014 this held up.",
            "name": "Priya Raman",
            "role": "Director of Operations, Northbeam Health"
          }
        ]
      }
    },
    "pricing": {
      "meta": {
        "title": "DollarWise Pricing | Financial Literacy for Everyone",
        "description": "Affordable plans to learn U.S. currency and financial management."
      },
      "hero": {
        "headline": "Simple pricing, clear learning outcomes",
        "subheadline": "Access our full curriculum covering Basic Financial Literacy through Federal Reserve System concepts at a price that fits your budget.",
        "highlights": [
          "No hidden fees",
          "Lifetime access to lessons"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "10,500+",
            "label": "Students enrolled globally"
          },
          {
            "value": "94%",
            "label": "Course completion rate"
          },
          {
            "value": "2 years",
            "label": "Average time to mastery"
          }
        ]
      },
      "pricing": {
        "eyebrow": "Pricing",
        "heading": "Simple, honest pricing",
        "sub": "Placeholder tiers \u2014 align with your real packaging.",
        "tiers": [
          {
            "name": "Self-Paced Learner",
            "price": "$0 / month",
            "period": "/mo",
            "description": "Free access to all curriculum modules. Ideal for students exploring financial basics.",
            "features": [
              "Basic Financial Literacy module",
              "Currency Denominations guide",
              "Progress tracking dashboard"
            ],
            "cta": {
              "label": "Choose Self-Paced Learner",
              "href": "/"
            },
            "featured": false
          },
          {
            "name": "Individual Plan",
            "price": "$9 / month",
            "period": "/mo",
            "description": "Full access with certificates and advanced management tools.",
            "features": [
              "All Self-Paced features included",
              "Currency Management workshop",
              "Certificate of Completion"
            ],
            "cta": {
              "label": "Choose Individual Plan",
              "href": "/"
            },
            "featured": true
          },
          {
            "name": "School License",
            "price": "$450 / year per class",
            "period": "/mo",
            "description": "Designed for classrooms and adult education groups.",
            "features": [
              "Admin dashboard for teachers",
              "Bulk account creation",
              "Federal Reserve System module access"
            ],
            "cta": {
              "label": "Choose School License",
              "href": "/"
            },
            "featured": false
          }
        ]
      },
      "cta": {
        "heading": "Ready to build your financial future?",
        "sub": "Select a plan below or contact our support team with questions about bulk enrollment options.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/"
        }
      }
    }
  }
} as const;

export const siteConfig = content.siteConfig;
export const nav = content.nav;
export const footer = content.footer;
export const pages = content.pages;
export default content;
