"""Cerebro — generated by code-engine.

A comprehensive AI research platform enabling users to explore and analyze various topics through a unified interface.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import search_service
from app.routers import dataset_service
from app.routers import access_control_service
from app.routers import session_service

app = FastAPI(title="Cerebro",
              description="A comprehensive AI research platform enabling users to explore and analyze various topics through a unified interface.")

init_db()

app.include_router(search_service.router)
app.include_router(dataset_service.router)
app.include_router(access_control_service.router)
app.include_router(session_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
