"""String Reverser — generated by code-engine.

Provides a simple API for reversing strings, useful in text processing and data manipulation.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import (
    debugging_service,
    input_limiter_service,
    performance_monitor_service,
    string_reverser_service,
    unicode_support_service,
)

app = FastAPI(title="String Reverser",
              description="Provides a simple API for reversing strings, useful in text processing and data manipulation.")

init_db()

app.include_router(string_reverser_service.router)
app.include_router(input_limiter_service.router)
app.include_router(debugging_service.router)
app.include_router(performance_monitor_service.router)
app.include_router(unicode_support_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
