"""PhoneFormatter — generated by code-engine.

A simple web service that takes a raw phone number as input and returns it in a standardized, human-readable format.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import country_code_repository, phone_formatter_service

app = FastAPI(title="PhoneFormatter",
              description="A simple web service that takes a raw phone number as input and returns it in a standardized, human-readable format.")

init_db()

app.include_router(phone_formatter_service.router)
app.include_router(country_code_repository.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
