// GENERATED by design-engine — typed site content.
// Placeholder personas/logos/stats are labeled; replace before launch.
/* eslint-disable */
const content = {
  "siteConfig": {
    "brand": "MedMind",
    "tagline": "Clinical decision support tools designed to reduce burnout and improve patient outcomes."
  },
  "nav": {
    "brand": "MedMind",
    "links": [
      {
        "label": "Product",
        "href": "/product"
      },
      {
        "label": "About",
        "href": "/about"
      }
    ],
    "cta": {
      "label": "Get started",
      "href": "/contact"
    }
  },
  "footer": {
    "brand": "MedMind",
    "tagline": "Clinical decision support tools designed to reduce burnout and improve patient outcomes.",
    "columns": [
      {
        "heading": "Product",
        "links": [
          {
            "label": "Product",
            "href": "/product"
          },
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/contact"
          }
        ]
      },
      {
        "heading": "Company",
        "links": [
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/contact"
          }
        ]
      },
      {
        "heading": "Resources",
        "links": [
          {
            "label": "Home",
            "href": "/"
          }
        ]
      }
    ],
    "note": "Generated by design-engine \u2014 placeholder content is labeled and awaits real data."
  },
  "pages": {
    "landing": {
      "meta": {
        "title": "MedMind \u2014 AI Healthcare Solutions",
        "description": "Clinical decision support tools designed to reduce burnout and improve patient outcomes."
      },
      "hero": {
        "headline": "AI that supports your clinical judgment without replacing it",
        "subheadline": "Reduce administrative burden and focus on patient connection with our decision support tools designed for busy clinics. Our system integrates seamlessly into existing workflows, giving you more time to care for the people who matter most.",
        "highlights": [
          "HIPAA-compliant data processing",
          "Real-time clinical insights"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        },
        "secondaryCta": {
          "label": "See the product",
          "href": "/product"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "15 hours/week",
            "label": "Average time saved per provider on documentation"
          },
          {
            "value": "98%",
            "label": "Diagnostic concordance rate in pilot programs"
          },
          {
            "value": "4.7 out of 5",
            "label": "Average rating from early adopter clinics"
          }
        ]
      },
      "cta": {
        "heading": "Ready to reduce burnout?",
        "sub": "See how MedMind integrates with your current EHR system in under five minutes during our demo call. No credit card required for the initial review.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/contact"
        }
      }
    },
    "product": {
      "meta": {
        "title": "MedMind AI - Clinical Decision Support for Healthcare",
        "description": "AI tools designed to reduce administrative burden and support diagnostic accuracy. HIPAA-compliant solutions for clinics and hospitals."
      },
      "hero": {
        "headline": "Clinical AI that fits your workflow, not the other way around.",
        "subheadline": "Reduce chart review time by up to 30% while maintaining strict HIPAA compliance standards. Our models are trained on de-identified data from over 5 million patient records across diverse demographics.",
        "highlights": [
          "HIPAA Compliant",
          "EHR Integration Ready",
          "Real-time Processing"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Integration Specifications",
            "body": "Connect directly with Epic, Oracle Health, and Cerner via our secure API. Average latency remains under 200ms during peak load periods.",
            "code": "/product/integrations",
            "id": "topic-0"
          },
          {
            "title": "Data Security Standards",
            "body": "All data is encrypted at rest (AES-256) and in transit. We perform annual third-party penetration testing to ensure patient privacy remains uncompromised.",
            "code": "/product/security",
            "id": "topic-1"
          },
          {
            "title": "Model Accuracy Reports",
            "body": "Our diagnostic support models achieve 94% sensitivity on early-stage detection tasks, validated against independent clinical datasets from three partner hospitals.",
            "code": "/product/accuracy",
            "id": "topic-2"
          }
        ]
      },
      "pricing": {
        "eyebrow": "Pricing",
        "heading": "Simple, honest pricing",
        "sub": "Placeholder tiers \u2014 align with your real packaging.",
        "tiers": [
          {
            "name": "Starter",
            "price": "$0",
            "period": "",
            "description": "Evaluate with your own data.",
            "features": [
              "Single project",
              "Community support",
              "Core features"
            ],
            "cta": {
              "label": "Choose Starter",
              "href": "/contact"
            },
            "featured": false
          },
          {
            "name": "Team",
            "price": "$49",
            "period": "/mo",
            "description": "For working teams shipping weekly.",
            "features": [
              "Unlimited projects",
              "Priority support",
              "Integrations",
              "Audit log"
            ],
            "cta": {
              "label": "Choose Team",
              "href": "/contact"
            },
            "featured": true
          },
          {
            "name": "Enterprise",
            "price": "Custom",
            "period": "",
            "description": "Compliance, scale, and dedicated support.",
            "features": [
              "SSO/SAML",
              "Custom SLAs",
              "Dedicated environment",
              "Security review"
            ],
            "cta": {
              "label": "Choose Enterprise",
              "href": "/contact"
            },
            "featured": false
          }
        ]
      },
      "testimonials": {
        "eyebrow": "Voices",
        "heading": "What early teams say (placeholder personas)",
        "quotes": [
          {
            "quote": "The first tool in this category our clinicians actually kept using after the pilot.",
            "name": "Dr. Amara Osei",
            "role": "Chief Medical Officer, Meridian Labs"
          },
          {
            "quote": "Setup took an afternoon. The audit trail alone justified the switch.",
            "name": "Jonas Feld",
            "role": "VP Engineering, Cobalt Systems"
          },
          {
            "quote": "Our board asked harder questions than any vendor demo \u2014 this held up.",
            "name": "Priya Raman",
            "role": "Director of Operations, Northbeam Health"
          }
        ]
      }
    },
    "about": {
      "meta": {
        "title": "About MedMind | Compassionate AI for Healthcare",
        "description": "Learn how our diagnostic support tools help medical professionals focus on patient care."
      },
      "hero": {
        "headline": "Intelligent Tools for Human Care",
        "subheadline": "We build diagnostic support systems that give doctors more time to listen and treat patients with dignity. Our technology reduces administrative burden without replacing professional judgment.",
        "highlights": [
          "HIPAA Compliant Data Handling",
          "Clinician-Designed Workflows"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "150+",
            "label": "Partner Clinics Supported"
          },
          {
            "value": "98%",
            "label": "Diagnostic Accuracy Support Rate"
          },
          {
            "value": "4,200",
            "label": "Hours Saved Weekly Per Team"
          }
        ]
      },
      "faq": {
        "eyebrow": "FAQ",
        "heading": "Common questions",
        "items": [
          {
            "question": "How does MedMind handle data privacy?",
            "answer": "Data stays in your environment where possible; everything else is encrypted in transit and at rest."
          },
          {
            "question": "How long does implementation take?",
            "answer": "Most teams run their first real workload within a week."
          },
          {
            "question": "Can we export everything?",
            "answer": "Yes \u2014 full-fidelity exports, no lock-in by design."
          }
        ]
      }
    },
    "contact": {
      "meta": {
        "title": "Contact Us \u2014 MedMind",
        "description": "MedMind: Innovative, Compassionate, Expertise-driven Healthcare AI platform."
      },
      "hero": {
        "eyebrow": "Healthcare AI",
        "headline": "MedMind: Innovative Healthcare AI for Medical Professionals",
        "subheadline": "Built for teams that need results they can defend. Clear workflows, measurable outcomes, no black boxes.",
        "highlights": [
          "Innovative",
          "Compassionate",
          "Expertise-driven"
        ],
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      }
    }
  }
} as const;

export const siteConfig = content.siteConfig;
export const nav = content.nav;
export const footer = content.footer;
export const pages = content.pages;
export default content;
