"""Hunter Run Tracker — generated by code-engine.

A service that records and queries gate outcomes for hunter runs, enabling hunters to track their progress and optimize future hunts.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import auth_service, csv_export_service, gate_outcome_service, hunt_service

app = FastAPI(title="Hunter Run Tracker",
              description="A service that records and queries gate outcomes for hunter runs, enabling hunters to track their progress and optimize future hunts.")

init_db()

app.include_router(hunt_service.router)
app.include_router(gate_outcome_service.router)
app.include_router(auth_service.router)
app.include_router(csv_export_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
