"""GPUcademy — generated by code-engine.

A web-based educational platform that teaches WebGPU compute shaders to adult beginners through hands-on learning and interactive content.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import auth_service, lesson_service, progress_service, quiz_service

app = FastAPI(title="GPUcademy",
              description="A web-based educational platform that teaches WebGPU compute shaders to adult beginners through hands-on learning and interactive content.")

init_db()

app.include_router(auth_service.router)
app.include_router(lesson_service.router)
app.include_router(progress_service.router)
app.include_router(quiz_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
