"""Hunter Run Outcome Tracker — generated by code-engine.

Provide a service for recording and querying gate outcomes of hunter runs, utilizing the organisation's metadata catalog.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import auth_service, gate_outcome_service

app = FastAPI(title="Hunter Run Outcome Tracker",
              description="Provide a service for recording and querying gate outcomes of hunter runs, utilizing the organisation's metadata catalog.")

init_db()

app.include_router(gate_outcome_service.router)
app.include_router(auth_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
