"""GPUcademy 2.0 — generated by code-engine.

A comprehensive online platform for learning WebGPU compute shaders, providing an updated curriculum with a focus on recent changes and advancements in the field.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import auth_service, curriculum_service, example_service, public_api, quiz_service

app = FastAPI(title="GPUcademy 2.0",
              description="A comprehensive online platform for learning WebGPU compute shaders, providing an updated curriculum with a focus on recent changes and advancements i")

init_db()

app.include_router(curriculum_service.router)
app.include_router(quiz_service.router)
app.include_router(auth_service.router)
app.include_router(example_service.router)
app.include_router(public_api.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
