"""GPUcademy 3.0 — generated by code-engine.

A comprehensive online platform for learning WebGPU compute shaders, providing an updated curriculum with a focus on recent changes and best practices.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import curriculum_service

app = FastAPI(title="GPUcademy 3.0",
              description="A comprehensive online platform for learning WebGPU compute shaders, providing an updated curriculum with a focus on recent changes and best practices")

init_db()

app.include_router(curriculum_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
