// GENERATED by design-engine — typed site content.
// Placeholder personas/logos/stats are labeled; replace before launch.
/* eslint-disable */
const content = {
  "siteConfig": {
    "brand": "LearnHub",
    "tagline": "Access practical skills and professional development resources."
  },
  "nav": {
    "brand": "LearnHub",
    "links": [
      {
        "label": "Product",
        "href": "/product"
      },
      {
        "label": "About",
        "href": "/about"
      }
    ],
    "cta": {
      "label": "Get started",
      "href": "/contact"
    }
  },
  "footer": {
    "brand": "LearnHub",
    "tagline": "Access practical skills and professional development resources.",
    "columns": [
      {
        "heading": "Product",
        "links": [
          {
            "label": "Product",
            "href": "/product"
          },
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/contact"
          }
        ]
      },
      {
        "heading": "Company",
        "links": [
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/contact"
          }
        ]
      },
      {
        "heading": "Resources",
        "links": [
          {
            "label": "Home",
            "href": "/"
          }
        ]
      }
    ],
    "note": "Generated by design-engine \u2014 placeholder content is labeled and awaits real data."
  },
  "pages": {
    "landing": {
      "meta": {
        "title": "Elevated Learning Hub | LearnHub",
        "description": "Access practical skills and professional development resources."
      },
      "hero": {
        "headline": "Master Practical Skills Online",
        "subheadline": "Access 150+ courses designed by industry experts. Build your knowledge with tools built for clarity.",
        "highlights": [
          "Self-paced learning modules",
          "Certification upon completion"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        },
        "secondaryCta": {
          "label": "See the product",
          "href": "/product"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "50,000+",
            "label": "Active Learners"
          },
          {
            "value": "2,400",
            "label": "Instructors Teaching"
          },
          {
            "value": "180+",
            "label": "Courses Created"
          }
        ]
      },
      "cta": {
        "heading": "Start Your Learning Journey Today",
        "sub": "Access our library of practical skills and professional development resources designed for your schedule.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/contact"
        }
      }
    },
    "product": {
      "meta": {
        "title": "LearnHub Product Page",
        "description": "Build courses and access learning materials with our accessible platform."
      },
      "hero": {
        "headline": "Create Courses. Access Knowledge.",
        "subheadline": "A structured environment for students to study at their own pace, instructors to share content easily, and teams to train staff efficiently.",
        "highlights": [
          "Host video lectures without bandwidth limits",
          "Grade assignments automatically with rubrics",
          "Access materials from any device"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "pricing": {
        "eyebrow": "Pricing",
        "heading": "Simple, honest pricing",
        "sub": "Placeholder tiers \u2014 align with your real packaging.",
        "tiers": [
          {
            "name": "Starter",
            "price": "$0",
            "period": "",
            "description": "Evaluate with your own data.",
            "features": [
              "Single project",
              "Community support",
              "Core features"
            ],
            "cta": {
              "label": "Choose Starter",
              "href": "/contact"
            },
            "featured": false
          },
          {
            "name": "Team",
            "price": "$49",
            "period": "/mo",
            "description": "For working teams shipping weekly.",
            "features": [
              "Unlimited projects",
              "Priority support",
              "Integrations",
              "Audit log"
            ],
            "cta": {
              "label": "Choose Team",
              "href": "/contact"
            },
            "featured": true
          },
          {
            "name": "Enterprise",
            "price": "Custom",
            "period": "",
            "description": "Compliance, scale, and dedicated support.",
            "features": [
              "SSO/SAML",
              "Custom SLAs",
              "Dedicated environment",
              "Security review"
            ],
            "cta": {
              "label": "Choose Enterprise",
              "href": "/contact"
            },
            "featured": false
          }
        ]
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Quickstart",
            "body": "Install, authenticate, and run your first request in under five minutes.",
            "code": "curl -X POST https://api.example.com/v1/run \\\n  -H 'Authorization: Bearer <token>'",
            "id": "topic-0"
          },
          {
            "title": "Core concepts",
            "body": "Projects, runs, and results \u2014 the three objects everything else builds on.",
            "id": "topic-1"
          },
          {
            "title": "API reference",
            "body": "Every endpoint, request shape, and error code, with examples.",
            "id": "topic-2"
          }
        ]
      },
      "testimonials": {
        "eyebrow": "Voices",
        "heading": "What early teams say (placeholder personas)",
        "quotes": [
          {
            "quote": "The first tool in this category our clinicians actually kept using after the pilot.",
            "name": "Dr. Amara Osei",
            "role": "Chief Medical Officer, Meridian Labs"
          },
          {
            "quote": "Setup took an afternoon. The audit trail alone justified the switch.",
            "name": "Jonas Feld",
            "role": "VP Engineering, Cobalt Systems"
          },
          {
            "quote": "Our board asked harder questions than any vendor demo \u2014 this held up.",
            "name": "Priya Raman",
            "role": "Director of Operations, Northbeam Health"
          }
        ]
      }
    },
    "about": {
      "meta": {
        "title": "About LearnHub | Our Mission and Team",
        "description": "Learn about our mission to make education accessible. Meet the team building tools for students, professors, and corporate trainers."
      },
      "hero": {
        "headline": "Building Better Learning Paths",
        "subheadline": "We create digital classrooms that work on any device, so you can focus on what matters: learning.",
        "highlights": [
          "Designed for clarity",
          "Built for accessibility"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "50,000+",
            "label": "Students enrolled annually"
          },
          {
            "value": "120",
            "label": "Certified instructors active today"
          },
          {
            "value": "4.8/5",
            "label": "Average course rating from users"
          }
        ]
      },
      "team": {
        "eyebrow": "Team",
        "heading": "The people behind it",
        "members": [
          {
            "name": "Alex Rivera",
            "role": "Founder & Lead Designer",
            "bio": "Former curriculum developer at State University, Alex spent ten years simplifying complex subjects for online learners. She focuses on interface design that reduces cognitive load."
          },
          {
            "name": "Jordan Lee",
            "role": "Head of Content Strategy",
            "bio": "With a background in corporate training, Jordan ensures our materials meet professional standards while remaining engaging for beginners and experts alike."
          },
          {
            "name": "Samir Patel",
            "role": "Lead Engineer",
            "bio": "Samir builds the platform's backend to handle high traffic without lag. He prioritizes security so user data remains private during every session."
          }
        ]
      },
      "faq": {
        "eyebrow": "FAQ",
        "heading": "Common questions",
        "items": [
          {
            "question": "How does LearnHub handle data privacy?",
            "answer": "Data stays in your environment where possible; everything else is encrypted in transit and at rest."
          },
          {
            "question": "How long does implementation take?",
            "answer": "Most teams run their first real workload within a week."
          },
          {
            "question": "Can we export everything?",
            "answer": "Yes \u2014 full-fidelity exports, no lock-in by design."
          }
        ]
      }
    },
    "contact": {
      "meta": {
        "title": "Contact Us | LearnHub",
        "description": "Reach out for course inquiries, partnership opportunities, or technical support."
      },
      "hero": {
        "headline": "Get in Touch with Us",
        "subheadline": "Have questions about courses, partnerships, or platform access? We are here to help you succeed.",
        "highlights": [
          "Student Support"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "15,000+",
            "label": "Active Learners Worldwide"
          },
          {
            "value": "240",
            "label": "Verified Courses Created"
          },
          {
            "value": "< 2 Hours",
            "label": "Average Support Response Time"
          }
        ]
      },
      "contactForm": {
        "eyebrow": "Contact",
        "heading": "Ready to start learning?",
        "sub": "Browse our catalog or contact support for guidance on your next step."
      },
      "testimonials": {
        "eyebrow": "Voices",
        "heading": "What early teams say (placeholder personas)",
        "quotes": [
          {
            "quote": "The first tool in this category our clinicians actually kept using after the pilot.",
            "name": "Dr. Amara Osei",
            "role": "Chief Medical Officer, Meridian Labs"
          },
          {
            "quote": "Setup took an afternoon. The audit trail alone justified the switch.",
            "name": "Jonas Feld",
            "role": "VP Engineering, Cobalt Systems"
          },
          {
            "quote": "Our board asked harder questions than any vendor demo \u2014 this held up.",
            "name": "Priya Raman",
            "role": "Director of Operations, Northbeam Health"
          }
        ]
      }
    }
  }
} as const;

export const siteConfig = content.siteConfig;
export const nav = content.nav;
export const footer = content.footer;
export const pages = content.pages;
export default content;
