"""DollarWise — generated by code-engine.

An interactive web platform that teaches adult beginners about U.S. currency through a structured curriculum, promoting financial literacy and independence.
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.db import init_db
from app.routers import lesson_service, user_service

app = FastAPI(title="DollarWise",
              description="An interactive web platform that teaches adult beginners about U.S. currency through a structured curriculum, promoting financial literacy and indepen")

init_db()

app.include_router(lesson_service.router)
app.include_router(user_service.router)


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


app.mount("/", StaticFiles(directory="static", html=True), name="ui")
