// GENERATED by design-engine — typed site content.
// Placeholder personas/logos/stats are labeled; replace before launch.
/* eslint-disable */
const content = {
  "siteConfig": {
    "brand": "GPUcademy",
    "tagline": "Updated curriculum for modern WebGPU compute shaders."
  },
  "nav": {
    "brand": "GPUcademy",
    "links": [
      {
        "label": "Product",
        "href": "/product"
      },
      {
        "label": "About",
        "href": "/about"
      },
      {
        "label": "Docs",
        "href": "/docs"
      }
    ],
    "cta": {
      "label": "Get started",
      "href": "/"
    }
  },
  "footer": {
    "brand": "GPUcademy",
    "tagline": "Updated curriculum for modern WebGPU compute shaders.",
    "columns": [
      {
        "heading": "Product",
        "links": [
          {
            "label": "Product",
            "href": "/product"
          },
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Docs",
            "href": "/docs"
          }
        ]
      },
      {
        "heading": "Company",
        "links": [
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/"
          }
        ]
      },
      {
        "heading": "Resources",
        "links": [
          {
            "label": "Documentation",
            "href": "/docs"
          },
          {
            "label": "Home",
            "href": "/"
          }
        ]
      }
    ],
    "note": "Generated by design-engine \u2014 placeholder content is labeled and awaits real data."
  },
  "pages": {
    "landing": {
      "meta": {
        "title": "GPUcademy \u2014 WebGPU Compute Shaders Curriculum",
        "description": "Updated curriculum for modern WebGPU compute shaders."
      },
      "hero": {
        "headline": "WebGPU Compute Shaders, Revised for Modern Standards",
        "subheadline": "We updated our lessons based on recent Working Group changes. Learn new memory barrier patterns and optimized dispatch structures used in production today.",
        "highlights": [
          "WGSL Syntax Updates Included",
          "Memory Management Best Practices",
          "Production-Ready Lab Environment"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        },
        "secondaryCta": {
          "label": "See the product",
          "href": "/product"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "12,000+",
            "label": "Developers Trained"
          },
          {
            "value": "94%",
            "label": "Course Completion Rate"
          },
          {
            "value": "3 Weeks",
            "label": "Average Time to Proficiency"
          }
        ]
      },
      "showcase": {
        "eyebrow": "Product",
        "heading": "The work, visible",
        "sub": "A schematic view \u2014 replace with real product imagery.",
        "panels": [
          {
            "label": "Throughput",
            "value": "12.4k/day"
          },
          {
            "label": "Accuracy",
            "value": "99.2%"
          },
          {
            "label": "Time saved",
            "value": "31 hrs/wk"
          }
        ],
        "caption": "Illustrative interface schematic generated by design-engine."
      },
      "cta": {
        "heading": "Start Your WebGPU Journey Today",
        "sub": "Access the updated curriculum and lab environment. No prior experience required beyond basic JavaScript knowledge.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/"
        }
      }
    },
    "product": {
      "meta": {
        "title": "GPUcademy 2.0 | WebGPU Compute Shaders",
        "description": "Updated curriculum for modern compute shaders."
      },
      "hero": {
        "headline": "GPUcademy 2.0: Updated Curriculum for Modern Compute Shaders",
        "subheadline": "We revised our lessons based on WGSL specification updates and browser implementation changes since the last release. Learn to write efficient, portable shaders today without vendor-specific hacks.",
        "highlights": [
          "WGSL v1.0 alignment",
          "Storage buffer optimization patterns",
          "Cross-browser compatibility focus"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "8,500+",
            "label": "Students Enrolled"
          },
          {
            "value": "32k+",
            "label": "Code Examples Reviewed"
          },
          {
            "value": "96%",
            "label": "Browser Compatibility Coverage"
          }
        ]
      },
      "showcase": {
        "eyebrow": "Product",
        "heading": "The work, visible",
        "sub": "A schematic view \u2014 replace with real product imagery.",
        "panels": [
          {
            "label": "Throughput",
            "value": "12.4k/day"
          },
          {
            "label": "Accuracy",
            "value": "99.2%"
          },
          {
            "label": "Time saved",
            "value": "31 hrs/wk"
          }
        ],
        "caption": "Illustrative interface schematic generated by design-engine."
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Quickstart",
            "body": "Install, authenticate, and run your first request in under five minutes.",
            "code": "curl -X POST https://api.example.com/v1/run \\\n  -H 'Authorization: Bearer <token>'",
            "id": "topic-0"
          },
          {
            "title": "Core concepts",
            "body": "Projects, runs, and results \u2014 the three objects everything else builds on.",
            "id": "topic-1"
          },
          {
            "title": "API reference",
            "body": "Every endpoint, request shape, and error code, with examples.",
            "id": "topic-2"
          }
        ]
      },
      "cta": {
        "heading": "Start Your Course Today",
        "sub": "Access the full curriculum for compute shader development on WebGPU platforms. Includes practical exercises and benchmark data from our internal labs.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/"
        }
      }
    },
    "about": {
      "meta": {
        "title": "About \u2014 GPUcademy",
        "description": "GPUcademy: Authoritative, Innovative, Practical Computer Science Education platform."
      },
      "hero": {
        "eyebrow": "Computer Science Education",
        "headline": "GPUcademy: Authoritative Computer Science Education for Software developers interested in GPU programming",
        "subheadline": "Built for teams that need results they can defend. Clear workflows, measurable outcomes, no black boxes.",
        "highlights": [
          "Authoritative",
          "Innovative",
          "Practical"
        ],
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "98%",
            "label": "Illustrative satisfaction rate"
          },
          {
            "value": "4x",
            "label": "Faster review cycles (placeholder)"
          },
          {
            "value": "24/7",
            "label": "Monitoring"
          },
          {
            "value": "SOC 2",
            "label": "Ready posture (target)"
          }
        ]
      },
      "team": {
        "eyebrow": "Team",
        "heading": "The people behind it",
        "members": [
          {
            "name": "Placeholder Founder",
            "role": "CEO",
            "bio": "Replace with a real bio \u2014 background, motivation, credibility."
          },
          {
            "name": "Placeholder Cofounder",
            "role": "CTO",
            "bio": "Replace with a real bio \u2014 technical track record."
          },
          {
            "name": "Placeholder Lead",
            "role": "Head of Product",
            "bio": "Replace with a real bio \u2014 domain expertise."
          }
        ]
      },
      "testimonials": {
        "eyebrow": "Voices",
        "heading": "What early teams say (placeholder personas)",
        "quotes": [
          {
            "quote": "The first tool in this category our clinicians actually kept using after the pilot.",
            "name": "Dr. Amara Osei",
            "role": "Chief Medical Officer, Meridian Labs"
          },
          {
            "quote": "Setup took an afternoon. The audit trail alone justified the switch.",
            "name": "Jonas Feld",
            "role": "VP Engineering, Cobalt Systems"
          },
          {
            "quote": "Our board asked harder questions than any vendor demo \u2014 this held up.",
            "name": "Priya Raman",
            "role": "Director of Operations, Northbeam Health"
          }
        ]
      },
      "faq": {
        "eyebrow": "FAQ",
        "heading": "Common questions",
        "items": [
          {
            "question": "How does GPUcademy handle data privacy?",
            "answer": "Data stays in your environment where possible; everything else is encrypted in transit and at rest."
          },
          {
            "question": "How long does implementation take?",
            "answer": "Most teams run their first real workload within a week."
          },
          {
            "question": "Can we export everything?",
            "answer": "Yes \u2014 full-fidelity exports, no lock-in by design."
          }
        ]
      }
    },
    "docs": {
      "meta": {
        "title": "Docs \u2014 GPUcademy",
        "description": "GPUcademy: Authoritative, Innovative, Practical Computer Science Education platform."
      },
      "hero": {
        "eyebrow": "Computer Science Education",
        "headline": "GPUcademy: Authoritative Computer Science Education for Software developers interested in GPU programming",
        "subheadline": "Built for teams that need results they can defend. Clear workflows, measurable outcomes, no black boxes.",
        "highlights": [
          "Authoritative",
          "Innovative",
          "Practical"
        ],
        "primaryCta": {
          "label": "Get started",
          "href": "/"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "98%",
            "label": "Illustrative satisfaction rate"
          },
          {
            "value": "4x",
            "label": "Faster review cycles (placeholder)"
          },
          {
            "value": "24/7",
            "label": "Monitoring"
          },
          {
            "value": "SOC 2",
            "label": "Ready posture (target)"
          }
        ]
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Quickstart",
            "body": "Install, authenticate, and run your first request in under five minutes.",
            "code": "curl -X POST https://api.example.com/v1/run \\\n  -H 'Authorization: Bearer <token>'",
            "id": "topic-0"
          },
          {
            "title": "Core concepts",
            "body": "Projects, runs, and results \u2014 the three objects everything else builds on.",
            "id": "topic-1"
          },
          {
            "title": "API reference",
            "body": "Every endpoint, request shape, and error code, with examples.",
            "id": "topic-2"
          }
        ]
      },
      "cta": {
        "heading": "See GPUcademy on your own data",
        "sub": "A 30-minute walkthrough with your team's real questions.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/"
        }
      }
    }
  }
} as const;

export const siteConfig = content.siteConfig;
export const nav = content.nav;
export const footer = content.footer;
export const pages = content.pages;
export default content;
