// GENERATED by design-engine — typed site content.
// Placeholder personas/logos/stats are labeled; replace before launch.
/* eslint-disable */
const content = {
  "siteConfig": {
    "brand": "GPUcademy",
    "tagline": "Master WebGPU compute shaders through hands-on projects and a comprehensive curriculum covering the API, debugging tools, and GPU architecture."
  },
  "nav": {
    "brand": "GPUcademy",
    "links": [
      {
        "label": "Product",
        "href": "/product"
      },
      {
        "label": "About",
        "href": "/about"
      },
      {
        "label": "Pricing",
        "href": "/pricing"
      }
    ],
    "cta": {
      "label": "Get started",
      "href": "/contact"
    }
  },
  "footer": {
    "brand": "GPUcademy",
    "tagline": "Master WebGPU compute shaders through hands-on projects and a comprehensive curriculum covering the API, debugging tools, and GPU architecture.",
    "columns": [
      {
        "heading": "Product",
        "links": [
          {
            "label": "Product",
            "href": "/product"
          },
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Pricing",
            "href": "/pricing"
          },
          {
            "label": "Contact",
            "href": "/contact"
          }
        ]
      },
      {
        "heading": "Company",
        "links": [
          {
            "label": "About",
            "href": "/about"
          },
          {
            "label": "Contact",
            "href": "/contact"
          }
        ]
      },
      {
        "heading": "Resources",
        "links": [
          {
            "label": "Home",
            "href": "/"
          }
        ]
      }
    ],
    "note": "Generated by design-engine \u2014 placeholder content is labeled and awaits real data."
  },
  "pages": {
    "landing": {
      "meta": {
        "title": "GPUcademy - Learn WebGPU Compute Shaders",
        "description": "Master WebGPU compute shaders through hands-on projects and a comprehensive curriculum covering the API, debugging tools, and GPU architecture."
      },
      "hero": {
        "headline": "Build High-Performance Graphics with WebGPU",
        "subheadline": "Learn compute shader fundamentals, debug profiling workflows, and master GPU architecture. Start coding your first kernel today.",
        "highlights": [
          "WebGPU Compute Shader API",
          "Debugging & Profiling Tools",
          "Hands-on Project Modules"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        },
        "secondaryCta": {
          "label": "See the product",
          "href": "/product"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "40+",
            "label": "Hours of Code Written by Students"
          },
          {
            "value": "12",
            "label": "Core Curriculum Weeks"
          },
          {
            "value": "95%",
            "label": "Course Completion Rate"
          }
        ]
      },
      "cta": {
        "heading": "Ready to write your first shader?",
        "sub": "Access the full curriculum and start building compute shaders immediately. No prior experience required beyond basic JavaScript knowledge.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/contact"
        }
      }
    },
    "product": {
      "meta": {
        "title": "GPUcademy | Master WebGPU Compute Shaders",
        "description": "Learn WebGPU compute shaders through hands-on projects and a comprehensive curriculum covering API fundamentals, architecture, and debugging."
      },
      "hero": {
        "headline": "Master WebGPU Compute Shaders with Practical Projects",
        "subheadline": "Build real applications using the full API. Learn fundamentals, memory management, and optimization directly in your browser or local environment.",
        "highlights": [
          "4 Core Modules covering Architecture to Debugging",
          "Hands-on projects for every lesson",
          "No prior CUDA experience required"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "docs": {
        "heading": "Documentation",
        "intro": "Everything needed to evaluate and integrate.",
        "topics": [
          {
            "title": "Compute Shaders Fundamentals",
            "body": "Start with the basics. Learn how to initialize a WebGPU context, bind buffers, and write your first WGSL compute shader code.",
            "code": "// Initialize device\nconst adapter = await navigator.gpu.requestAdapter();\n",
            "id": "topic-0"
          },
          {
            "title": "WebGPU Compute Shader API",
            "body": "Deep dive into workgroups, atomic operations, and storage textures. Understand how to pass data between compute shaders and render pipelines.",
            "code": "// DispatchWorkgroup\ncommandEncoder.dispatchWorkgroups(1024);\n",
            "id": "topic-1"
          },
          {
            "title": "Debugging and Profiling",
            "body": "Use built-in tools to inspect shader logs, analyze memory usage, and identify bottlenecks before deployment.",
            "code": "// Check for errors\nconsole.log(device.getError());\n",
            "id": "topic-2"
          },
          {
            "title": "GPU Architecture & Optimization",
            "body": "Understand the hardware behind the API. Learn about compute units, memory hierarchy, and how to write shaders that run efficiently on consumer GPUs.",
            "code": "// Optimize for latency\nconst pipeline = device.createComputePipeline();\n",
            "id": "topic-3"
          }
        ]
      },
      "pricing": {
        "eyebrow": "Pricing",
        "heading": "Simple, honest pricing",
        "sub": "Placeholder tiers \u2014 align with your real packaging.",
        "tiers": [
          {
            "name": "Starter",
            "price": "$0",
            "period": "",
            "description": "Evaluate with your own data.",
            "features": [
              "Single project",
              "Community support",
              "Core features"
            ],
            "cta": {
              "label": "Choose Starter",
              "href": "/contact"
            },
            "featured": false
          },
          {
            "name": "Team",
            "price": "$49",
            "period": "/mo",
            "description": "For working teams shipping weekly.",
            "features": [
              "Unlimited projects",
              "Priority support",
              "Integrations",
              "Audit log"
            ],
            "cta": {
              "label": "Choose Team",
              "href": "/contact"
            },
            "featured": true
          },
          {
            "name": "Enterprise",
            "price": "Custom",
            "period": "",
            "description": "Compliance, scale, and dedicated support.",
            "features": [
              "SSO/SAML",
              "Custom SLAs",
              "Dedicated environment",
              "Security review"
            ],
            "cta": {
              "label": "Choose Enterprise",
              "href": "/contact"
            },
            "featured": false
          }
        ]
      }
    },
    "about": {
      "meta": {
        "title": "About GPUcademy | Our Approach",
        "description": "Learn WebGPU compute shaders through a practical curriculum covering API fundamentals, debugging tools, and GPU architecture."
      },
      "hero": {
        "headline": "Master WebGPU Compute Shaders Through Practical Projects",
        "subheadline": "Our curriculum moves beyond theory. You will build performant shaders using our structured lessons on the WebGPU Compute Shader API, fundamental concepts, profiling techniques, and underlying GPU architecture.",
        "highlights": [
          "Hands-on coding exercises in every module",
          "Real-world debugging scenarios included",
          "Direct access to compute shader documentation"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "250+",
            "label": "Active Learners Enrolled This Quarter"
          },
          {
            "value": "400",
            "label": "Compute Shaders Completed by Students"
          },
          {
            "value": "8",
            "label": "Core Curriculum Modules"
          }
        ]
      },
      "testimonials": {
        "eyebrow": "Voices",
        "heading": "What early teams say (placeholder personas)",
        "quotes": [
          {
            "quote": "The first tool in this category our clinicians actually kept using after the pilot.",
            "name": "Dr. Amara Osei",
            "role": "Chief Medical Officer, Meridian Labs"
          },
          {
            "quote": "Setup took an afternoon. The audit trail alone justified the switch.",
            "name": "Jonas Feld",
            "role": "VP Engineering, Cobalt Systems"
          },
          {
            "quote": "Our board asked harder questions than any vendor demo \u2014 this held up.",
            "name": "Priya Raman",
            "role": "Director of Operations, Northbeam Health"
          }
        ]
      }
    },
    "pricing": {
      "meta": {
        "title": "GPUcademy Pricing | WebGPU Compute Shader Training Plans",
        "description": "Transparent pricing for mastering WebGPU compute shaders. Choose self-paced or mentorship tracks."
      },
      "hero": {
        "headline": "Pricing and Enrollment Options",
        "subheadline": "Select a plan that matches your development goals. Access the full curriculum, debugging tools, and project templates.",
        "eyebrow": "",
        "highlights": [],
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "pricing": {
        "eyebrow": "Pricing",
        "heading": "Simple, honest pricing",
        "sub": "Placeholder tiers \u2014 align with your real packaging.",
        "tiers": [
          {
            "name": "Self-Paced Learner",
            "price": "$49/month",
            "period": "/mo",
            "description": "Access to all video lessons and code exercises.",
            "features": [
              "WebGPU Compute Shader API documentation access",
              "Compute Shaders Fundamentals module included",
              "Debugging and Profiling tools guide",
              "Community forum access"
            ],
            "cta": {
              "label": "Choose Self-Paced Learner",
              "href": "/contact"
            },
            "featured": false
          },
          {
            "name": "Project Mentorship",
            "price": "$149/month",
            "period": "/mo",
            "description": "Guided learning with code reviews for your projects.",
            "features": [
              "Everything in Self-Paced Learner",
              "Weekly 30-minute Q&A sessions",
              "GPU Architecture deep-dive lectures",
              "Priority support ticket queue"
            ],
            "cta": {
              "label": "Choose Project Mentorship",
              "href": "/contact"
            },
            "featured": true
          },
          {
            "name": "Team License",
            "price": "$49/user/month",
            "period": "/mo",
            "description": "Deploy the curriculum across your engineering team.",
            "features": [
              "Centralized dashboard for all users",
              "Admin controls and progress tracking",
              "Custom domain support included",
              "Dedicated Slack channel access"
            ],
            "cta": {
              "label": "Choose Team License",
              "href": "/contact"
            },
            "featured": false
          }
        ]
      },
      "cta": {
        "heading": "Start Your Training Today",
        "sub": "Enroll in the Self-Paced plan or contact us for Team pricing details. No hidden fees, just practical learning materials.",
        "primaryCta": {
          "label": "Book a walkthrough",
          "href": "/contact"
        }
      }
    },
    "contact": {
      "meta": {
        "title": "Get Support - GPUcademy",
        "description": "Contact our team about WebGPU compute shader courses, curriculum questions, or enterprise training."
      },
      "hero": {
        "headline": "Talk to Our Team About Your Learning Goals",
        "subheadline": "Have specific questions about the Compute Shader API? Need help debugging your first kernel? We are here to answer them directly.",
        "highlights": [
          "Direct access to our instructors"
        ],
        "eyebrow": "",
        "primaryCta": {
          "label": "Get started",
          "href": "/contact"
        }
      },
      "stats": {
        "stats": [
          {
            "value": "500+",
            "label": "Students Enrolled"
          },
          {
            "value": "12",
            "label": "Core Modules Available"
          },
          {
            "value": "98%",
            "label": "Course Completion Rate"
          }
        ]
      },
      "faq": {
        "eyebrow": "FAQ",
        "heading": "Common questions",
        "items": [
          {
            "question": "How long does the curriculum take to complete?",
            "answer": "Most learners finish in about six weeks. You can adjust your pace based on availability."
          },
          {
            "question": "Do you offer corporate training for my team?",
            "answer": "Yes, we build custom plans for engineering groups and research labs. Reach out to discuss requirements."
          },
          {
            "question": "Can I get a refund if the course isn't right for me?",
            "answer": "We offer a thirty-day money-back guarantee on all standard enrollments."
          }
        ]
      }
    }
  }
} as const;

export const siteConfig = content.siteConfig;
export const nav = content.nav;
export const footer = content.footer;
export const pages = content.pages;
export default content;
